[package]
name = "gateway-mfr"
version = "0.1.5-dev"
authors = ["Marc Nijdam <marc@helium.com>"]
edition = "2018"
license = "Apache-2.0"

[[bin]]
name = "gateway_mfr"
path = "src/main.rs"
doc = false

[dependencies]
structopt = "0"
anyhow = "1"
semver = "0"
serde = "1"
serde_json = "1"
angry-purple-tiger = "0"
ecc608-linux = "0"
helium-crypto = {git = "https://github.com/helium/helium-crypto-rs", tag="v0.2.2"}

